services:
  - type: web
    name: sistema-grafiprinter
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: MIGRATE_ON_START
        value: "true"
